### ISSUE TITLE
override cache store

### ISSUE THREAD

**Issue by rsands2801** [avramovic/aws-cron-job#1]
We use redis to power our servers cache and would to have all cache stored there.  Is there a reason we override to file storage?

**Comment by avramovic** [comment]
@rsands2801 Hm, I wanted all instances to be independent when deciding which one will run the cron job. I think the list of all instances could be cached in a cache all instances are sharing (such as redis), but since each instance is also caching it's own `instance-id`, it should be different for each one. If we're gonna cache it in a shared cache then each instance should use different key to store it's own instance id and not let other instances overwrite it. Correct me if I'm wrong.

I'm open for any suggestions, PRs, etc :)

**Comment by rsands2801** [comment]
Thanks for coming back @avramovic 

I think there is something to consider - what is the over head of calling the magic ip?  It seems like a very basic call that would not introduce much lag?

Another idea is you could user the instance local IP or host name and use that as the key to store the instance ID?

**Comment by avramovic** [comment]
@rsands2801 Well I'm not sure, I just didn't want all my instances to keep hitting the magic IP as the result will always be the same :)

But I should definitely make caching optional and make users decide which cache storage they want to use.

**Comment by rsands2801** [comment]
@avramovic with a cache being on the instance for the server list it actually causes multiple servers to believe it is the leader.

We deploy our systems very often and there is a time that the cache is in an invalid state as a new instance was added to the pool.

For the instance list it only works properly if you use a central cache for the master list - as one takes over that would instantly invalidate the other instance.

**Comment by avramovic** [comment]
@rsands2801 Yes, you're right. I didn't notice that as my system haven't changed instances for a while :) and everything still works. I've merged your PR. Thank you for your contribution!

**Comment by rsands2801** [comment]
Awesome thanks @avramovic - we are rolling out the servers with new version now :)
